name: MAUI Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Installeer MAUI workloads (Android)
        run: dotnet workload install maui-android

      - name: Herstel NuGet packages
        run: dotnet restore Grocery.App/Grocery.App.csproj -p:TargetFramework=net8.0-android

      - name: Bouw de Android app
        run: dotnet build Grocery.App/Grocery.App.csproj --framework net8.0-android --runtime android-arm64 --configuration Release --no-restore

      - name: Publiceer Android .apk
        run: dotnet publish Grocery.App/Grocery.App.csproj --framework net8.0-android --runtime android-arm64 -c Release -o ./output/android

      - name: Upload build-artifact (.apk)
        uses: actions/upload-artifact@v4
        with:
          name: maui-android-apk
          path: ./output/android/*.apk
